# Site settings
title: Newton Three
email: info@newtonthree.com
url: http://newtownthree.com
description: "We build businesses with top notch operations and tomorrow's technologies."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#111111'
  links: '#219ab3'

# Footer settings
footer: © 2016 Gaussian Holdings LLC.

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: 
  - title: facebook
    url:


# Build settings
markdown: kramdown
permalink: pretty
